array_concat () accept
array_constr (_,_) accept
array_debugarray (_) accept
array_join (_,_) accept
array_pop (_) accept
array_push (_) accept
array_reverse (_) accept
array_shift (_) accept
array_slice (_,_,_) accept
array_sort (_,_) accept
array_toString (_) accept
array_isArray (_,_) accept
array_splice (_,_,_) accept
array_splice (_,_,_) accept
array_unshift (_) accept
array_indexOf (_,_,_) accept
array_lastIndexOf (_,_,_) accept
array_every (_,_,_) accept
array_some (_,_,_) accept
array_forEach (_,_,_) accept
array_map (_,_,_) accept
array_filter (_,_,_) accept
array_reduce (_,_,_) accept
array_reduceRight (_,_,_) accept
boolean_constr_nonew (_,_) accept
boolean_constr (_,_) accept
boolean_valueOf (_) accept
boolean_toString (_) accept
builtin_isFinite (_,_) accept
builtin_isNaN (_,_) accept
builtin_parseFloat (_,_) accept
builtin_parseInt (_,_,_) accept
builtin_to_number (_,_) accept
builtin_to_string (_,_) accept
function_apply (_,_,_) accept
function_toString (_) accept
math_max (_) accept
math_min (_) accept
math_abs (_,_) accept
math_sqrt (_,_) accept
math_sin (_,_) accept
math_cos (_,_) accept
math_tan (_,_) accept
math_asin (_,_) accept
math_acos (_,_) accept
math_atan (_,_) accept
math_atan2 (_,_,_) accept
math_exp (_,_) accept
math_log (_,_) accept
math_ceil (_,_) accept
math_floor (_,_) accept
math_round (_,_) accept
math_pow (_,_,_) accept
math_random (_) accept
number_constr_nonew (_,_) accept
number_constr (_,_) accept
number_valueOf (_) accept
number_toString (_,_) accept
number_toFixed (_,_) accept
number_toExponential (_,_) accept
number_toPrecision (_,_) accept
string_charAt (_,_) accept
string_charCodeAt (_,_) accept
string_concat (_,_) accept
string_constr_nonew (_,_) accept
string_constr (_,_) accept
string_fromCharCode (_) accept
string_localeCompare (_,_) accept
string_slice (_,_,_) accept
string_substring (_,_,_) accept
string_toLowerCase (_) accept
string_toUpperCase (_) accept
string_indexOf () accept
string_lastIndexOf () accept
string_valueOf (_) accept
string_split (_,_,_) accept
string_trim (_) accept