array_concat () unspecified
array_constr (_,_) unspecified
array_debugarray (_) unspecified
array_join (_,_) unspecified
array_pop (_) unspecified
array_push (_) unspecified
array_reverse (_) unspecified
array_shift (_) unspecified
array_slice (_,_,_) unspecified
array_sort (_,_) unspecified
array_toString (_) unspecified
array_isArray (_,_) unspecified
array_splice (_,_,_) unspecified
array_splice (_,_,_) unspecified
array_unshift (_) unspecified
array_indexOf (_,_,_) unspecified
array_lastIndexOf (_,_,_) unspecified
array_every (_,_,_) unspecified
array_some (_,_,_) unspecified
array_forEach (_,_,_) unspecified
array_map (_,_,_) unspecified
array_filter (_,_,_) unspecified
array_reduce (_,_,_) unspecified
array_reduceRight (_,_,_) unspecified
boolean_constr_nonew (_,_) unspecified
boolean_constr (_,_) unspecified
boolean_valueOf (_) unspecified
boolean_toString (_) unspecified
builtin_isFinite (_,_) unspecified
builtin_isNaN (_,_) unspecified
builtin_parseFloat (_,_) unspecified
builtin_parseInt (_,_,_) unspecified
builtin_to_number (_,_) unspecified
builtin_to_string (_,_) unspecified
function_apply (_,_,_) unspecified
function_toString (_) unspecified
math_max (_) unspecified
math_min (_) unspecified
math_abs (_,_) unspecified
math_sqrt (_,_) unspecified
math_sin (_,_) unspecified
math_cos (_,_) unspecified
math_tan (_,_) unspecified
math_asin (_,_) unspecified
math_acos (_,_) unspecified
math_atan (_,_) unspecified
math_atan2 (_,_,_) unspecified
math_exp (_,_) unspecified
math_log (_,_) unspecified
math_ceil (_,_) unspecified
math_floor (_,_) unspecified
math_round (_,_) unspecified
math_pow (_,_,_) unspecified
math_random (_) unspecified
number_constr_nonew (_,_) unspecified
number_constr (_,_) unspecified
number_valueOf (_) unspecified
number_toString (_,_) unspecified
number_toFixed (_,_) unspecified
number_toExponential (_,_) unspecified
number_toPrecision (_,_) unspecified
string_charAt (_,_) unspecified
string_charCodeAt (_,_) unspecified
string_concat (_,_) unspecified
string_constr_nonew (_,_) unspecified
string_constr (_,_) unspecified
string_fromCharCode (_) unspecified
string_localeCompare (_,_) unspecified
string_slice (_,_,_) unspecified
string_substring (_,_,_) unspecified
string_toLowerCase (_) unspecified
string_toUpperCase (_) unspecified
string_indexOf () unspecified
string_lastIndexOf () unspecified
string_valueOf (_) unspecified
string_split (_,_,_) unspecified
string_trim (_) unspecified